src/Controllers/CakeManagementController.cs
using System.Linq;
using SaniatsCakeShop.Models;
using SaniatsCakeShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace SaniatsCakeShop.Controllers
{
    [Authorize(Roles = "Administrator")]
   // [Authorize(Policy = "DeletePie")]
    public class CakeManagementController: Controller
    {
        private readonly ICakeRepository _cakeRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CakeManagementController(ICakeRepository cakeRepository, ICategoryRepository categoryRepository)
        {
            _cakeRepository = cakeRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult Index()
        {
            var cakes = _cakeRepository.AllCakes.OrderBy(p => p.CakeId);
            return View(cakes);
        }

        public IActionResult AddCake()
        {
            var categories = _categoryRepository.AllCategories;
            var cakeEditViewModel = new CakeEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                CategoryId = categories.FirstOrDefault().CategoryId
            };
            return View(cakeEditViewModel);
        }

        [HttpPost]
        public IActionResult AddCake(CakeEditViewModel cakeEditViewModel)
        {
         /*
            //Basic validation
            if (ModelState.IsValid)
            {
                _cakeRepository.CreateCake(cakeEditViewModel.Cake);
                return RedirectToAction("Index");
            }
            return View(cakeEditViewModel);

            */


            if (ModelState.GetValidationState("Cake.Price") == ModelValidationState.Valid
               || cakeEditViewModel.Cake.Price < 0)
                ModelState.AddModelError(nameof(cakeEditViewModel.Cake.Price), "The price of the cake should be higher than 0");

            if (cakeEditViewModel.Cake.IsCakeOfTheWeek && !cakeEditViewModel.Cake.InStock)
                ModelState.AddModelError(nameof(cakeEditViewModel.Cake.IsCakeOfTheWeek), "Only cakes that are in stock should be Most Sold Cake of the Week");

            if (ModelState.IsValid)
            {
                _cakeRepository.CreateCake(cakeEditViewModel.Cake);
                return RedirectToAction("Index");
            }

            return View(cakeEditViewModel);
        }

        public IActionResult EditCake(int cakeId)
        {
            var categories = _categoryRepository.AllCategories;

            var cake = _cakeRepository.AllCakes.FirstOrDefault(p => p.CakeId == cakeId);

            var cakeEditViewModel = new CakeEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                Cake = cake,
                CategoryId = cake.CategoryId
            };

            var item = cakeEditViewModel.Categories.FirstOrDefault(c => c.Value == cake.CategoryId.ToString());
            item.Selected = true;

            return View(cakeEditViewModel);
        }

        [HttpPost]
        public IActionResult EditCake(CakeEditViewModel cakeEditViewModel)
        {
            cakeEditViewModel.Cake.CategoryId = cakeEditViewModel.CategoryId;

            if (ModelState.IsValid)
            {
                _cakeRepository.UpdateCake(cakeEditViewModel.Cake);
                return RedirectToAction("Index");
            }
            return View(cakeEditViewModel);
        }

        [HttpPost]
        public IActionResult DeleteCake(string cakeId)
        {
            return View();
        }

    }
}

src/Views/CakeManagement/AddCake.cshtml
@model CakeEditViewModel

<h2>Create a new Cake</h2>

<form asp-controller="CakeManagement" asp-action="AddCake" method="post" class="form-horizontal" role="form">
    <h4>Enter the cake details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Cake.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.Name" class="form-control" />
            <span asp-validation-for="Cake.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ShortDescription" class="form-control" />
            <span asp-validation-for="Cake.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.LongDescription" class="form-control" />
            <span asp-validation-for="Cake.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.Price" class="form-control" />
            <span asp-validation-for="Cake.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Cake.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ImageUrl" class="form-control" />
            <span asp-validation-for="Cake.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.InStock" class="form-control" />
            <span asp-validation-for="Cake.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.IsCakeOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.IsCakeOfTheWeek" class="form-control" />
            <span asp-validation-for="Cake.IsCakeOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create cake" />
        </div>
    </div>
</form>

src/Views/CakeManagement/EditCake.cshtml
@model CakeEditViewModel

<h2>Edit cake</h2>

<form asp-controller="CakeManagement" asp-action="EditCake" method="post" class="form-horizontal" role="form">
    <h4>Update the cake details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Cake.CakeId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.CakeId" class="form-control" />@*readonly="readonly"*@
            <span asp-validation-for="Cake.CakeId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.Name" class="form-control" />
            <span asp-validation-for="Cake.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ShortDescription" class="form-control" />
            <span asp-validation-for="Cake.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.LongDescription" class="form-control" />
            <span asp-validation-for="Cake.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.Price" class="form-control" />
            <span asp-validation-for="Cake.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Cake.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.ImageUrl" class="form-control" />
            <span asp-validation-for="Cake.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.InStock" class="form-control" />
            <span asp-validation-for="Cake.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cake.IsCakeOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Cake.IsCakeOfTheWeek" class="form-control" />
            <span asp-validation-for="Cake.IsCakeOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Update cake" />
        </div>
    </div>
</form>

src/Views/CakeManagement/Index.cshtml
@model IEnumerable<Cake>

<h2>Cake Management</h2>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">No cakes at this point :()</td></tr>
}
else
{
    <table class="table table-condensed table-bordered">
        <tr>
            <th>Cake ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>In stock</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        @foreach (var ce in Model)
        {
            <tr>
                <td>@ce.CakeId</td>
                <td><img src="@ce.ImageThumbnailUrl" /></td>
                <td>@ce.Name</td>
                <td><input type="checkbox" asp-for="@ce.InStock" />
                <td>@ce.Price</td>
                <td>
                    <form asp-action="DeleteCake" asp-route-cakeId="@ce.CakeId" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditCake" asp-route-cakeId="@ce.CakeId">Edit</a>
                        <button type="submit" onclick="return confirm('Do you really want to delete this cake?');" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
    </table>
}
<p>
    <a class="btn btn-primary" asp-action="AddCake">Add new cake</a>
</p>